//
// Created by lx on 2021/4/18.
//

#ifndef WISHBOUND_INTERFACE_BUS_CONTROLLER_TRANSACTION_H
#define WISHBOUND_INTERFACE_BUS_CONTROLLER_TRANSACTION_H


class bus_controller_if {

};


#endif //WISHBOUND_INTERFACE_BUS_CONTROLLER_TRANSACTION_H
